name: jagis_lints
description: A starting point for Dart libraries or applications.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 0.0.1

environment:
  sdk: 3.9.0

dev_dependencies:
  dart_code_metrics_presets: 2.25.1
